language: generic

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=nukosuke/terraform-provider-zendesk
  matrix:
    - MODULE=trigger-autoreply

before_install:
  - docker pull $DOCKER_IMAGE

script:
  - |
    docker run --rm -it -v $(pwd)/examples/$MODULE:/terraform -v $(pwd)/modules:/modules \
    -e TF_VAR_ZENDESK_ACCOUNT=$ZENDESK_ACCOUNT \
    -e TF_VAR_ZENDESK_EMAIL=$ZENDESK_EMAIL \
    -e TF_VAR_ZENDESK_TOKEN=$ZENDESK_TOKEN \
    $DOCKER_IMAGE init

  - |
    docker run --rm -it -v $(pwd)/examples/$MODULE:/terraform -v $(pwd)/modules:/modules \
    -e TF_VAR_ZENDESK_ACCOUNT=$ZENDESK_ACCOUNT \
    -e TF_VAR_ZENDESK_EMAIL=$ZENDESK_EMAIL \
    -e TF_VAR_ZENDESK_TOKEN=$ZENDESK_TOKEN \
    $DOCKER_IMAGE plan
